### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by ryanto** [dollarshaveclub/ember-router-scroll#133]
Looks like some tags are missing from Github when comparing to published versions on npm.

![image](https://user-images.githubusercontent.com/89411/39680609-9b112d2a-5170-11e8-90ba-41d9106c931f.png)

**Comment by yowainwright** [comment]
@rwwagner90 We automated the publish task [here](https://github.com/dollarshaveclub/ember-router-scroll/commit/4150589b6c91f82fec92a616e40409dfe37621b7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21), and it was unfortunately removed [here](https://github.com/dollarshaveclub/ember-router-scroll/commit/36381092723f55dece326cc35295646120ff2e66).

In favor of not having to constantly publish tags on our end, we should add the automated publish task back to our CI build, something I'd be open to a PR for.

**Comment by rwwagner90** [comment]
@yowainwright can you please just push them, instead of giving me a hard time on this? If you give me npm rights, I'd be happy to manually push all the things, but since I did not do these releases, and I do not have permissions, I do not have the tags. It's super easy to just `git push --tags`. I'm trying my hardest to keep things afloat here, but having a very hard time with all the restrictions.

**Comment by ryanto** [comment]
I can take a shot at wiring up CI to push tags back to github. I've never done it before, but it's on my todo list with our OSS so I might as well learn how 😛

**Comment by yowainwright** [comment]
@ryanto checkout the [script](https://github.com/dollarshaveclub/ember-router-scroll/commit/4150589b6c91f82fec92a616e40409dfe37621b7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21)—that's all that is needed. 

The script linked in my comment above will allow us to never have to do this again.  

Request my review and I will approve. 👍

**Comment by ryanto** [comment]
Cool & thank you! For the existing tags (v0.5 and v0.6) can we get those pushed back to GH? I had some trouble with the addon last night and wanted to debug with various versions.

**Comment by jakiestfu** [comment]
@rwwagner90 @ryanto We will push the tags, but we also reserve the right to prefer to move forward with an actual solution that works for everyone rather than handle these things as they come, especially if we've had these problems solved at some point. Thanks for the feedback and contributions from you two!

**Comment by ryanto** [comment]
Of course! Automated solutions are the best! :)

**Comment by yowainwright** [comment]
@ryanto

- the missing tags were added 
- git tags will now be automated for future versions

Thanks for pointing out this issue! 🙏

**Comment by ryanto** [comment]
Awesome, thanks man!
